### ISSUE TITLE
'online' event not emitted with connection to server by node-xmpp-client library

### ISSUE THREAD

**Issue by tongxiang** [tongxiang/converser#1]
Attempted to temporarily implement the `node-xmpp-client` library within the `www` initialization file of the express app. Created XMPP users with two different domains, and confirmed that their registration worked by sending messages using the Adium chat client. Code below: 
### Installation and setup

`npm install`. Place `config.js` in the top-level converser directory. Run using `npm start`. For verbose debug levels, run using `DEBUG=* npm start`. 
### Implementation code

```
/**
 * Creating an XMPP client. 
 */
var Client = require('node-xmpp-client');
var config = require('../config');

var client = new Client({
  jid: config.botUsername,
  password: config.botPassword, 
  host: 'jabb3r.org'
})

client.on('online', function() {
  console.log('online');
  client.send('<presence/>');
})

// Echoing response via stanza 
client.on('stanza', function (stanza) {
  console.log('Incoming stanza: ', stanza.toString());
  if (stanza.is('message') &&
    // Important: never reply to errors!
    (stanza.attrs.type !== 'error')) {
    // Swap addresses...
    stanza.attrs.to = stanza.attrs.from
    delete stanza.attrs.from
    // and send back
    console.log('Sending response: ' + stanza.root().toString())
    client.send(stanza)
  }
})

client.on('error', function (e) {
  console.error(e)
})

```

Running high debug verbosity with `DEBUG=* npm start` indicates that the socket connection with the target XMPP server was started, but still the `online` event is never fired, and `online` is never logged. (The server times out at 150 seconds before anything can be logged.) 

I've wondered if this was a server-side issue, and have tried two different XMPP servers: `jabb3r.org` and `chatme.im` with two different accounts. (Both servers have had their certificates tested, have high security ratings by [this XMPP server aggregation site](https://xmpp.net/), but this could entirely be a security certificate issue). Have had no success. Have also attempted using a simplified version of `node-xmpp-client`, or `simple-xmpp`, with no success. 

This could be a security issue. Below is the high-verbosity logs from starting the app to the point where the app times out. 
### Logs

```
tong% DEBUG=* npm start

> converser@0.0.0 start /Users/tongxiang/Code/converser
> node ./bin/www

  express:router:route new / +0ms
  express:router:layer new / +5ms
  express:router:route get / +4ms
  express:router:layer new / +0ms
  express:router:route new / +3ms
  express:router:layer new / +0ms
  express:router:route get / +1ms
  express:router:layer new / +0ms
  express:application set "x-powered-by" to true +3ms
  express:application set "etag" to 'weak' +1ms
  express:application set "etag fn" to [Function: wetag] +1ms
  express:application set "env" to 'production' +0ms
  express:application set "query parser" to 'extended' +0ms
  express:application set "query parser fn" to [Function: parseExtendedQueryString] +0ms
  express:application set "subdomain offset" to 2 +1ms
  express:application set "trust proxy" to false +0ms
  express:application set "trust proxy fn" to [Function: trustNone] +1ms
  express:application booting in production mode +0ms
  express:application set "view" to [Function: View] +0ms
  express:application set "views" to '/Users/tongxiang/Code/converser/views' +0ms
  express:application set "jsonp callback name" to 'callback' +0ms
  express:application set "view cache" to true +0ms
  express:router use / query +4ms
  express:router:layer new / +0ms
  express:router use / expressInit +0ms
  express:router:layer new / +1ms
  express:router use / logger +0ms
  express:router:layer new / +0ms
  express:router use / jsonParser +70ms
  express:router:layer new / +0ms
  express:router use / urlencodedParser +5ms
  express:router:layer new / +0ms
  express:router use / cookieParser +1ms
  express:router:layer new / +0ms
  express:router use / serveStatic +0ms
  express:router:layer new / +0ms
  express:router use / router +0ms
  express:router:layer new / +1ms
  express:router use /message router +0ms
  express:router:layer new /message +0ms
  express:router use / <anonymous> +0ms
  express:router:layer new / +0ms
  express:router use / <anonymous> +0ms
  express:router:layer new / +0ms
  express:application set "port" to 3000 +0ms
  node-stringprep Cannot load StringPrep-0.7.3 bindings (using fallback). You may need to `npm install node-stringprep` +122ms
  node-stringprep Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:450:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at bindings (/Users/tongxiang/Code/converser/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/tongxiang/Code/converser/node_modules/node-stringprep/index.js:10:39)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10) +0ms
username:  converserbot@jabb3r.org
 password:  WaG$ho{z!2@
  node-stringprep Operation does not exist +870ms nodeprep [TypeError: Cannot read property 'StringPrep' of undefined]
  node-stringprep Operation does not exist +1ms nameprep [TypeError: Cannot read property 'StringPrep' of undefined]
  xmpp:client:session start socket connection +8ms
  xmpp:connection setup socket +1ms
  xmpp:connection use lazy socket +3ms
  xmpp:connection setup stream +0ms
  converser:server Listening on port 3000 +3ms
{ [Error: connect ETIMEDOUT 144.76.16.171:5222]
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '144.76.16.171',
  port: 5222 }
```
### resources I've looked into:
- https://github.com/node-xmpp/node-xmpp-client/pull/61
- https://github.com/node-xmpp/node-xmpp-client/issues/77
- http://stackoverflow.com/questions/22566024/cant-connect-to-gcm-using-node-xmpp-client
- http://stackoverflow.com/questions/9952075/unable-to-connect-to-xmpp-server-using-node-xmpp
- https://github.com/node-xmpp/node-xmpp-client/issues/83

**Comment by tongxiang** [comment]
Requisite code is on the `node-xmpp-client` branch.

**Comment by tongxiang** [comment]
Small scope, non-trivial implementation, I hope.

Note that there needs to be another google talk user here.

Looking to create an XMPP HTTP gateway in nodejs. So, build a nodejs app that binds to an XMPP server (you can probably use Google Talk [gchat] to keep it simple) and allows a third party to POST or GET messages to it. For example:

POST /message/send?message=Does+this+work&to=chris@crisistextline.org

Would send the message "Does this work" to "chris@crisistextline.org" via the XMPP server. Basically, we're creating a bridge that abstracts the XMPP logic.

Bonus points of you can do the reverse: when receiving an inbound message from the XMPP server, allow for a configurable POST-back to some other third party notifying them what the message is.

This project matters because we're looking to integrate with FB messenger in the VERY near future, and they've opened up messenger as an XMPP api-like thinger. It's anintentionally open challenge--send along any questions you may have or ways I can help clarify.

GOOGLE TALK USER
username: converserbot@gmail.com
password: arcane depths & monkey

WHAT IS XMPP?
- https://www.quora.com/What-is-XMPP-and-how-does-it-work
- https://www.quora.com/Can-you-explain-how-XMPP-works-to-a-15-year-old
  - your client (adsium) sends packets (XML) to a router (XMPP server) that determines who get to see a copy of that packet.
  - "presence" —> when you want to chat with someone, you have to subscribe to them. When you login to the XMPP server, the status message is delivered to anyone who has subscribed to your presence.

TUTORIALS / RESOURCES
https://www.simonholywell.com/post/2013/02/create-a-node-js-google-talk-bot-pt1/
http://stackoverflow.com/questions/4349577/connecting-to-google-talk-over-xmpp-on-node-js
http://stackoverflow.com/questions/21288057/unable-to-connect-to-gtalk-with-node-js-and-node-xmpp

https://gist.github.com/gobengo/790919

https://github.com/node-xmpp/node-xmpp

how to create xmpp client using Node.js
http://blog.cubettech.com/xmpp-chat-using-node-js

I think I should probably use Node-XMPP-client, then.
- create environmental variables with the credentials of the google talk account
- create a node-xmpp client
- use that client to connect with an XMPP server

warnings
- set the timeout of the bot to be much greater than 60 seconds

The Simon Holywell tutorial is describing building a bot that binds to a google talk account. You accept the subscription of this bot's account, and that allows you to accept messages to it, as well as message others.

JABBER
SO Jabber is an XMPP server. You can use an IM client to communicate via thie Jabber server. And in fact, it seems like this dude built a chatbot on Jabber with AIM.

So I should:
- Created two jabber accounts, converserbot@jabb3r.org and tongxiang@jabb3r.org through hot-chili
- Install a jabber client

problems
- client is not connecting, console.log that is run client.on('connect') isn't showing up. Why???? no one fucking has any idea.
  - https://github.com/node-xmpp/node-xmpp-client/pull/61
  - https://github.com/node-xmpp/node-xmpp-client/issues/77
  - http://stackoverflow.com/questions/22566024/cant-connect-to-gcm-using-node-xmpp-client
  - http://stackoverflow.com/questions/9952075/unable-to-connect-to-xmpp-server-using-node-xmpp
  - https://github.com/node-xmpp/node-xmpp-client/issues/83
    - could be the specific kind of XMPP server, i.e. open fire or prosody
  - https://github.com/node-xmpp/node-xmpp-client/issues/118
- also occasionally getting this error when we start it up: (node) crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
  - but getting this error when we don't specify a host in the connection.

problem thoughts
- is this a problem with the server host?
- maybe this is a problem with the certificate of jabb3r.org, which is not immediately trusted. So maybe it's failing silently there.
- going to try simple-xmpp, a fork off of node-simple-xmpp
- tried using high debug setting with:  DEBUG=\* nam start and got a lot more shit <— where I left off
  - none of the install string shit worked.
- there's a reason why there aren't a lot of SO posts talking about this problem—most likely, there's a problem with the WAY in which I'm connecting with XMPP.
  - things I should check on tomorrow:
    - do I understand the XMPP paradigm well enough? Did I get the domain and host correctly? Sure, I changed the host to be jabb3r.org, and then errors disappeared, but maybe I didn't understand the host paradigm well enough.
    - What does DEBUG=\* do? Prints out debug statements from the library.
    - What is the high debug level reporting, in this case?

SECURITY
- First, attempting to register accounts with servers through PSI. But continually, I'm either unable to connect to the server, or their certificate fails some sort of authenticity test.
- After attempting to create accounts through PSI with many, many of the servers, it seems like a lot of them fail the certificate test. So if my computer doesn't trust the certificate, maybe on a low level the node app won't connect to it, or else fail silently?
- So: let's try overriding this, and accepting the certificate for one account: https://support.apple.com/kb/PH18677?locale=en_US
  - So I changed my certificate trust settings for jabb3r.org, and chatme.im
  - now my mac will always trust them
  - this didn't work
- Can I manipulate security settings using "preferred SaslMechanism"?
- attempted to install STartSSL's certificate, didn't work: http://www.jabber.org/faq.html, http://www.startssl.com/certs/ca.crt.

next steps
- understand what's going on with the arguments that are called. What's going on with the security settings?
  - arguments to client: http://node-xmpp.org/doc/client.html
- think through how I would lay out the app if it were working—for instance, how do I eliminate the timeout?
  - how to extend timeout of request library: https://github.com/DoSomething/ds-mdata-responder/pull/257/files
- Next step: deploying own XMPP server and debugging it from that end. https://github.com/node-xmpp/node-xmpp-server
  - another server option: https://www.process-one.net/en/ejabberd/downloads/
  - another server option: http://prosody.im/
  - figuring out where the response from the server is supposed to be caught in the node-xmpp-client library. Figuring that out.

Arguments to Client() Object:
- jid [String]: The jid of the user you wish to log in as. If no host parameter provided an SRV lookup will be performed on the domain (where possible).
  - SRV: service record, part of DNS which defines the hostname and port number of a service for a specified service.
- password [String]: Password to be used for login
- host [String]: The host where the the XMPP server is located
  - Pretty sure I can log into any XMPP server host with my jabber ID.
- preferredSaslMechanism [String]: The preferred SASL mechanism to use for authentication (actually just `preferred`)
  - framework for authentication and security in protocols.
  - difference between, and definitions of, SASL and SSL: http://stackoverflow.com/questions/11347304/security-authentication-ssl-vs-sasl
- bosh [Object]: An object to specify BOSH options
  - "Bidirectional-streams Over Synchronous HTTP" - transport protocol that emulates a bidirectional stream between two entities (such as a client and a server) by using multiple synchronous HTTP request/response pairs without requiring the use of polling or asynchronous chunking"
  - more bandwidth efficient and responsive than things like AJAX for applications which requires both push and pull communications
  - important for specialized XMPP applications - http://www.isode.com/whitepapers/xmpp-bosh.html
  - If you're using XMPP chat over a browser, rather than a desktop client, there's now ay for the server to push messages to you. It must use bosh.
- url [String]: The BOSH URL endpoint to use (used in preference to a socket if provided)
- wait [Int]: See wait attribute
  - this doesn't appear as a param able to be taken in in `Client.js`.
- websocket [Object]: An object to specify WebSocket options
  - doesn't appear as a param within Client.js
  - looks like you can use WebSocket rather than BOSH.
- url [String]: The WebSocket URL endpoint to use (used in preference to a socket and BOSH endpoint if provided)
- register [Boolean]: Create a new account on the server
- port [Int]: Port number to use for socket connection
- reconnect [Boolean]: Reconnect on disconnection
- legacySSL [Boolean]: Connect to the legacy SSL port (5223) - requires at least the host to be specified
- credentials [Boolean]: TLS or SSL key and certificate credentials
  - how necessary is this? What is this for?
- actAs [String]: if admin user act on behalf of another user
- disallowTLS [Boolean]: Prevent upgrading of the connection to a secure one using TLS
- oauth2_token [String]: OAuth2 token e.g. used for logging into google talk
- oauth2_auth [String]: OAuth2 namespace e.g. used for logging into google talk
- api_key [String]: For logging into Facebook XMPP account
- access_token [String]: For logging into Facebook XMPP account
- wait [String]: The HTTP-BIND wait value (in seconds). This is the time the server will wait before returning an empty result for a request. Default is 10 seconds.

So it seems like the options provided  lot of ways to configure the protocols you're connecting to a server with. If you don't specify these, what are the defaults?

Documentation for this library is super out of date. Some examples they mention are gone.

Trying examples within the repository
- anonymous.js -
  - From xmpp.org: An XMPP server implementation SHOULD NOT enable the SASL ANONYMOUS mechanism by default, but instead SHOULD force the administrator of a given service to explicitly enable support in the context of that deployment.
  - When a client authenticates using SASL ANONYMOUS, an XMPP server SHOULD assign a temporary, unique bare JID localpart@domain.tld to the client. Although the method for ensuring the uniqueness of the localpart is a matter of implementation, it is RECOMMENDED for the localpart to be a UUID as specified in RFC 4122 [4].
- answer_bot.js -
  - Requires a JID component. WTF is a JID component?

how should I structure this?
Make the client initialization a separate file. And then, pass the client object from place to place.
